spring.application.name=calculator-web-application
server.port= 9090
server.servlet.context-path=/calculator

logging.level.root=INFO
logging.level.com.example.calculator=DEBUG

spring.jackson.default-property-inclusion=non_null
spring.mvc.throw-exception-if-no-handler-found=true
