---
- name: Deploy WAR to Tomcat
  hosts: tomcat
  become: yes

  tasks:

    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes

    - name: Remove old WAR
      file:
        path: /opt/tomcat/webapps/calculator.war 
        state: absent

    - name: Copy WAR
      copy:
        src: ../target/calculator.war 
        dest: /opt/tomcat/webapps/calculator.war 

    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh
