---
- name: Deploy WAR from Nexus to Tomcat
  hosts: tomcat
  become: yes

  vars:
    nexus_url: "http://65.0.205.16:8081/repository/calculator-web-application-Snap/com/example/calculator-web-application/0.0.1-SNAPSHOT/calculator-0.0.1-20260714.140003-2.war"

  tasks:

    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes

    - name: Remove old WAR
      file:
        path: /opt/tomcat/webapps/calculator.war
        state: absent

    - name: Remove old exploded application
      file:
        path: /opt/tomcat/webapps/calculator
        state: absent

    - name: Download WAR from Nexus
      get_url:
        url: "{{ nexus_url }}"
        dest: /opt/tomcat/webapps/calculator.war
        mode: '0644'

    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh
